# Generated by Django 4.2.6 on 2024-05-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_followers',
            new_name='user_following',
        ),
    ]
