# Generated by Django 4.2.6 on 2024-05-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
