# Generated by Django 4.2.6 on 2024-05-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_profile_name_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
